#!/usr/bin/env python3
"""JiuZhang Math Model - Low VRAM Training Script
Generated by LowVRAMTrainer
Hardware: Apple Silicon detected (MPS supported)
Effective batch size: 32
"""

import os
import json
import time
from pathlib import Path

os.environ["WANDB_DISABLED"] = "true"

# Memory-efficient imports
try:
    from unsloth import FastLanguageModel
    HAS_UNSLOTH = True
except ImportError:
    HAS_UNSLOTH = False
    print("Unsloth not installed. Using standard transformers.")

import torch
from transformers import (
    AutoModelForCausalLM, AutoTokenizer, 
    BitsAndBytesConfig,
    TrainingArguments, Trainer,
    DataCollatorForSeq2Seq,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from datasets import load_dataset

# Configuration
MODEL_NAME = "Qwen/Qwen3.5-0.8B"
DATA_PATH = "jiuzhang_distilled.jsonl"
OUTPUT_DIR = "/private/var/folders/h0/64ycsy616rbb9rsm15zj4tpm0000gn/T/pytest-of-fred/pytest-70/test_generate_all_scripts0/model"
CHECKPOINT_DIR = os.path.join(OUTPUT_DIR, "checkpoints")
MAX_SEQ_LENGTH = 1024
BATCH_SIZE = 1
GRADIENT_ACCUMULATION = 32
EPOCHS = 5
LEARNING_RATE = 0.0001
LORA_R = 16
LORA_ALPHA = 8
TARGET_MODULES = ["q_proj", "v_proj"]

print("=" * 60)
print("JiuZhang Math Model - Low VRAM Training")
print("=" * 60)
print(f"Hardware: Apple Silicon detected (MPS supported)")
print(f"Effective batch size: {BATCH_SIZE * GRADIENT_ACCUMULATION}")
print(f"LoRA rank: {LORA_R}")
print(f"4-bit quantization: True")
print(f"CPU offloading: True")
print("=" * 60)

# Device setup
device = "mps"
compute_dtype = torch.float16

# Quantization config (4-bit for minimal memory)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=compute_dtype,
    bnb_4bit_use_double_quant=True,
)

# Load model with quantization
print("Loading model with 4-bit quantization...")

# Resolve ModelScope model to local path if needed
MODEL_PATH = MODEL_NAME
if "True":
    try:
        from modelscope import snapshot_download
        MODEL_PATH = snapshot_download(MODEL_NAME)
        print(f"ModelScope model resolved to: {MODEL_PATH}")
    except ImportError:
        print("modelscope not installed, falling back to HuggingFace path")
    except Exception as e:
        print(f"ModelScope download failed: {e}, trying HuggingFace path")

if HAS_UNSLOTH:
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=MODEL_PATH,
        max_seq_length=MAX_SEQ_LENGTH,
        dtype=None,
        load_in_4bit=True,
    )
else:
    tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_PATH,
        quantization_config=bnb_config,
        device_map="auto" if not True else {"": device},
        torch_dtype=compute_dtype,
    )

# Apply LoRA
print("Applying LoRA adapters...")
if HAS_UNSLOTH:
    model = FastLanguageModel.get_peft_model(
        model,
        r=LORA_R,
        lora_alpha=LORA_ALPHA,
        lora_dropout=LORA_DROPOUT,
        target_modules=TARGET_MODULES,
        bias="none",
        use_gradient_checkpointing=True,
        random_state=42,
    )
else:
    model = prepare_model_for_kbit_training(model)
    lora_config = LoraConfig(
        r=LORA_R,
        lora_alpha=LORA_ALPHA,
        lora_dropout=0.05,
        target_modules=TARGET_MODULES,
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

# Load dataset
print("Loading training data...")
dataset = load_dataset("json", data_files=DATA_PATH, split="train")

def format_chatml(example):
    return {
        "text": tokenizer.apply_chat_template(example["messages"], tokenize=False)
    }

dataset = dataset.map(format_chatml)
print(f"Loaded {len(dataset)} training samples")

# Training arguments (memory-optimized)
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION,
    warmup_ratio=0.05,
    max_steps=-1,
    num_train_epochs=EPOCHS,
    learning_rate=LEARNING_RATE,
    weight_decay=0.01,
    lr_scheduler_type="cosine",
    logging_steps=10,
    save_steps=100,
    save_total_limit=3,  # Keep only last 3 checkpoints
    output_dir=OUTPUT_DIR,
    seed=42,
    bf16=compute_dtype == torch.bfloat16,
    fp16=compute_dtype == torch.float16,
    optim="adamw_8bit",
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    dataloader_num_workers=0,  # Avoid memory overhead from workers
    report_to="none",
)

# Trainer
trainer = Trainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    args=training_args,
    data_collator=DataCollatorForSeq2Seq(tokenizer=tokenizer, padding=True),
)

# Resume from checkpoint if specified
resume_from = None
# No checkpoint to resume
if resume_from and Path(resume_from).exists():
    print(f"Resuming from checkpoint: {resume_from}")

# Training
print("\nStarting training...")
print(f"Expected time: ~{len(dataset) * EPOCHS // (BATCH_SIZE * GRADIENT_ACCUMULATION)} steps")
start_time = time.time()

trainer.train(resume_from_checkpoint=resume_from)

elapsed = time.time() - start_time
print(f"\nTraining completed in {elapsed/60:.1f} minutes")

# Save model
print("Saving model...")
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

# Save LoRA adapter only (much smaller)
lora_dir = os.path.join(OUTPUT_DIR, "lora-adapter")
model.save_pretrained(lora_dir)
print(f"LoRA adapter saved to {lora_dir}")

# Export to GGUF for Ollama
try:
    if HAS_UNSLOTH:
        model.save_pretrained_gguf(OUTPUT_DIR, tokenizer)
        print("GGUF model exported for Ollama")
except Exception as e:
    print(f"GGUF export failed: {e}")
    print("You can manually convert using: python -m transformers.commands.pt_to_tf")

print("\n" + "=" * 60)
print("Training complete!")
print(f"Model: {OUTPUT_DIR}")
print(f"LoRA adapter: {lora_dir}")
print(f"Training time: {elapsed/60:.1f} minutes")
print("=" * 60)
