#!/usr/bin/env python3
"""JiuZhang End-to-End Math Model Training Pipeline.

Complete workflow:
  1. Merge all training data (curriculum + self-correction + rejection sampling)
  2. Download Qwen3.5-0.8B from ModelScope
  3. Train with QLoRA (low VRAM optimized)
  4. Export to GGUF + Ollama

Usage:
  python train_math_model_end_to_end.py                    # Full pipeline
  python train_math_model_end_to_end.py --step prepare     # Only prepare data
  python train_math_model_end_to_end.py --step download    # Only download model
  python train_math_model_end_to_end.py --step train       # Only train
  python train_math_model_end_to_end.py --step export      # Only export to Ollama
"""

import json
import os
import subprocess
import sys
import time
from pathlib import Path

# Configuration
MODEL_NAME = "Qwen/Qwen3.5-0.8B"
OUTPUT_DIR = "jiuzhang-math-0.8b"
DATA_FILES = [
    "jiuzhang_curriculum.jsonl",
    "jiuzhang_self_correction.jsonl",
    "jiuzhang_rejection_sampling.jsonl",
]
MERGED_DATA = "jiuzhang_merged_training.jsonl"
MAX_SEQ_LENGTH = 1024
LORA_R = 16
LORA_ALPHA = 32
EPOCHS = 3
BATCH_SIZE = 1
GRADIENT_ACCUMULATION = 32
LEARNING_RATE = 2e-4


def step_prepare_data():
    """Merge all training data into a single file."""
    print("=" * 60)
    print("Step 1: Preparing Training Data")
    print("=" * 60)
    
    merged = []
    for f in DATA_FILES:
        if not Path(f).exists():
            print(f"  WARNING: {f} not found, skipping")
            continue
        with open(f) as fh:
            for line in fh:
                line = line.strip()
                if line:
                    try:
                        sample = json.loads(line)
                        # Ensure messages format
                        if "messages" in sample:
                            merged.append(sample)
                    except json.JSONDecodeError:
                        continue
    
    # Shuffle
    import random
    random.seed(42)
    random.shuffle(merged)
    
    # Write merged data
    with open(MERGED_DATA, "w") as fh:
        for sample in merged:
            fh.write(json.dumps(sample, ensure_ascii=False) + "\n")
    
    print(f"  Merged {len(merged)} samples from {len(DATA_FILES)} files")
    print(f"  Output: {MERGED_DATA}")
    print(f"  File size: {Path(MERGED_DATA).stat().st_size / 1024:.1f} KB")
    
    # Statistics
    categories = {}
    for sample in merged:
        cat = sample.get("category", sample.get("stage_name", "unknown"))
        categories[cat] = categories.get(cat, 0) + 1
    
    print("\n  Category distribution:")
    for cat, count in sorted(categories.items(), key=lambda x: -x[1]):
        bar = "#" * (count // 10)
        print(f"    {cat:20s}: {count:5d} {bar}")
    
    return len(merged)


def step_download_model():
    """Download model from ModelScope."""
    print("=" * 60)
    print("Step 2: Downloading Model from ModelScope")
    print("=" * 60)
    print(f"  Model: {MODEL_NAME}")
    
    try:
        from modelscope import snapshot_download
        print("  Downloading... (this may take a while)")
        model_path = snapshot_download(MODEL_NAME)
        print(f"  Model downloaded to: {model_path}")
        return model_path
    except ImportError:
        print("  ERROR: modelscope not installed")
        print("  Install with: pip install modelscope")
        return None
    except Exception as e:
        print(f"  ERROR: Download failed: {e}")
        print("  Trying HuggingFace fallback...")
        try:
            from huggingface_hub import snapshot_download as hf_download
            model_path = hf_download(MODEL_NAME)
            print(f"  Model downloaded from HuggingFace: {model_path}")
            return model_path
        except Exception as e2:
            print(f"  ERROR: HuggingFace also failed: {e2}")
            return None


def step_generate_training_script(model_path=None):
    """Generate the actual training script."""
    print("=" * 60)
    print("Step 3: Generating Training Script")
    print("=" * 60)
    
    actual_model = model_path or MODEL_NAME
    device_info = _detect_device()
    
    # Build script using string replacement to avoid % conflicts
    script_lines = []
    def add(line=""):
        script_lines.append(line)
    
    add('#!/usr/bin/env python3')
    add('"""JiuZhang Math Model Training Script — QLoRA on Qwen3.5-0.8B')
    add('')
    add('Auto-generated by train_math_model_end_to_end.py')
    add('"""')
    add('')
    add('import os')
    add('import json')
    add('import time')
    add('from pathlib import Path')
    add('')
    add('os.environ["WANDB_DISABLED"] = "true"')
    add('')
    add('# Detect device')
    add('import torch')
    add('if torch.backends.mps.is_available():')
    add('    device = "mps"')
    add('    print("Using Apple Silicon MPS")')
    add('elif torch.cuda.is_available():')
    add('    device = "cuda"')
    add('    print("Using CUDA: " + torch.cuda.get_device_name(0))')
    add('else:')
    add('    device = "cpu"')
    add('    print("Using CPU (will be slow)")')
    add('')
    add('# Try unsloth first, fallback to standard transformers')
    add('HAS_UNSLOTH = False')
    add('try:')
    add('    from unsloth import FastLanguageModel')
    add('    HAS_UNSLOTH = True')
    add('    print("Unsloth available — using optimized training")')
    add('except (ImportError, NotImplementedError) as e:')
    add('    if "GPU" in str(e):')
    add('        print("Unsloth not supported on this device — using standard transformers")')
    add('    else:')
    add('        print("Unsloth not installed — using standard transformers")')
    add('')
    add('from transformers import (')
    add('    AutoModelForCausalLM, AutoTokenizer,')
    add('    BitsAndBytesConfig, TrainingArguments, Trainer,')
    add('    DataCollatorForSeq2Seq,')
    add(')')
    add('from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training')
    add('from datasets import load_dataset')
    add('')
    add('# Configuration')
    add('MODEL_PATH = "%s"' % actual_model)
    add('DATA_PATH = "%s"' % MERGED_DATA)
    add('OUTPUT_DIR = "%s"' % OUTPUT_DIR)
    add('MAX_SEQ_LENGTH = %d' % MAX_SEQ_LENGTH)
    add('BATCH_SIZE = %d' % BATCH_SIZE)
    add('GRADIENT_ACCUMULATION = %d' % GRADIENT_ACCUMULATION)
    add('EPOCHS = %d' % EPOCHS)
    add('LEARNING_RATE = %s' % LEARNING_RATE)
    add('LORA_R = %d' % LORA_R)
    add('LORA_ALPHA = %d' % LORA_ALPHA)
    add('')
    add('print("=" * 60)')
    add('print("JiuZhang Math Model Training")')
    add('print("=" * 60)')
    add('print("Model: " + MODEL_PATH)')
    add('print("Data: " + DATA_PATH)')
    add('print("Output: " + OUTPUT_DIR)')
    add('print("Device: " + device)')
    add('print("LoRA r=%d, alpha=%d" % (LORA_R, LORA_ALPHA))')
    add('print("Effective batch: %d" % (BATCH_SIZE * GRADIENT_ACCUMULATION))')
    add('print("Epochs: %d" % EPOCHS)')
    add('print("Learning rate: %s" % LEARNING_RATE)')
    add('print("=" * 60)')
    add('')
    add('# Load tokenizer')
    add('print("Loading tokenizer...")')
    add('tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)')
    add('if tokenizer.pad_token is None:')
    add('    tokenizer.pad_token = tokenizer.eos_token')
    add('')
    add('# Quantization config')
    add('bnb_config = BitsAndBytesConfig(')
    add('    load_in_4bit=True,')
    add('    bnb_4bit_quant_type="nf4",')
    add('    bnb_4bit_compute_dtype=torch.float16,')
    add('    bnb_4bit_use_double_quant=True,')
    add(')')
    add('')
    add('# Load model')
    add('print("Loading model with 4-bit quantization...")')
    add('if HAS_UNSLOTH:')
    add('    model, tokenizer = FastLanguageModel.from_pretrained(')
    add('        model_name=MODEL_PATH,')
    add('        max_seq_length=MAX_SEQ_LENGTH,')
    add('        dtype=None,')
    add('        load_in_4bit=True,')
    add('    )')
    add('else:')
    add('    model = AutoModelForCausalLM.from_pretrained(')
    add('        MODEL_PATH,')
    add('        quantization_config=bnb_config,')
    add('        device_map="auto",')
    add('        torch_dtype=torch.float16,')
    add('    )')
    add('')
    add('# Apply LoRA')
    add('print("Applying LoRA adapters...")')
    add('if HAS_UNSLOTH:')
    add('    model = FastLanguageModel.get_peft_model(')
    add('        model,')
    add('        r=LORA_R,')
    add('        lora_alpha=LORA_ALPHA,')
    add('        lora_dropout=0.05,')
    add('        target_modules=["q_proj", "v_proj", "k_proj", "o_proj",')
    add('                       "gate_proj", "up_proj", "down_proj"],')
    add('        bias="none",')
    add('        use_gradient_checkpointing=True,')
    add('        random_state=42,')
    add('    )')
    add('else:')
    add('    model = prepare_model_for_kbit_training(model)')
    add('    lora_config = LoraConfig(')
    add('        r=LORA_R,')
    add('        lora_alpha=LORA_ALPHA,')
    add('        lora_dropout=0.05,')
    add('        target_modules=["q_proj", "v_proj", "k_proj", "o_proj",')
    add('                       "gate_proj", "up_proj", "down_proj"],')
    add('        bias="none",')
    add('        task_type="CAUSAL_LM",')
    add('    )')
    add('    model = get_peft_model(model, lora_config)')
    add('')
    add('model.print_trainable_parameters()')
    add('')
    add('# Load and format data')
    add('print("Loading training data...")')
    add('dataset = load_dataset("json", data_files=DATA_PATH, split="train")')
    add('print("Loaded %d samples" % len(dataset))')
    add('')
    add('def format_chatml(example):')
    add('    messages = example["messages"]')
    add('    text = tokenizer.apply_chat_template(messages, tokenize=False)')
    add('    return {"text": text}')
    add('')
    add('dataset = dataset.map(format_chatml, remove_columns=dataset.column_names)')
    add('')
    add('# Training arguments')
    add('training_args = TrainingArguments(')
    add('    output_dir=OUTPUT_DIR,')
    add('    per_device_train_batch_size=BATCH_SIZE,')
    add('    gradient_accumulation_steps=GRADIENT_ACCUMULATION,')
    add('    warmup_ratio=0.05,')
    add('    num_train_epochs=EPOCHS,')
    add('    learning_rate=LEARNING_RATE,')
    add('    weight_decay=0.01,')
    add('    lr_scheduler_type="cosine",')
    add('    logging_steps=10,')
    add('    save_steps=100,')
    add('    save_total_limit=3,')
    add('    fp16=True,')
    add('    optim="adamw_8bit",')
    add('    seed=42,')
    add('    report_to="none",')
    add(')')
    add('')
    add('# Data collator')
    add('data_collator = DataCollatorForSeq2Seq(')
    add('    tokenizer=tokenizer,')
    add('    padding=True,')
    add('    max_length=MAX_SEQ_LENGTH,')
    add('    return_tensors="pt",')
    add(')')
    add('')
    add('# Train')
    add('print("Starting training...")')
    add('start_time = time.time()')
    add('')
    add('trainer = Trainer(')
    add('    model=model,')
    add('    train_dataset=dataset,')
    add('    args=training_args,')
    add('    data_collator=data_collator,')
    add(')')
    add('')
    add('trainer.train()')
    add('')
    add('elapsed = time.time() - start_time')
    add('print("Training completed in %.1f minutes" % (elapsed/60))')
    add('')
    add('# Save')
    add('print("Saving model to " + OUTPUT_DIR + "...")')
    add('model.save_pretrained(OUTPUT_DIR)')
    add('tokenizer.save_pretrained(OUTPUT_DIR)')
    add('')
    add('# Export GGUF if unsloth')
    add('if HAS_UNSLOTH:')
    add('    print("Exporting to GGUF...")')
    add('    model.save_pretrained_gguf(OUTPUT_DIR, tokenizer)')
    add('    print("GGUF model exported to " + OUTPUT_DIR)')
    add('')
    add('print("=" * 60)')
    add('print("Training complete!")')
    add('print("Model saved to: " + OUTPUT_DIR)')
    add('print("=" * 60)')
    
    script = "\n".join(script_lines)
    
    script_path = "train_jiuzhang_math.py"
    Path(script_path).write_text(script, encoding="utf-8")
    print(f"  Training script generated: {script_path}")
    print(f"  Run with: python {script_path}")
    return script_path


def step_export_to_ollama(model_dir=None):
    """Export trained model to Ollama."""
    print("=" * 60)
    print("Step 4: Exporting to Ollama")
    print("=" * 60)
    
    model_dir = model_dir or OUTPUT_DIR
    
    # Check if GGUF exists
    gguf_files = list(Path(model_dir).glob("*.gguf"))
    if not gguf_files:
        print(f"  No GGUF file found in {model_dir}")
        print("  Trying to convert with llama.cpp...")
        print("  (Manual step: convert model to GGUF first)")
        return False
    
    gguf_path = gguf_files[0]
    model_name = "jiuzhang-math-0.8b"
    
    modelfile = 'FROM ' + str(gguf_path) + '''

PARAMETER temperature 0.1
PARAMETER top_p 0.9
PARAMETER num_ctx 4096
PARAMETER presence_penalty 0.2
PARAMETER frequency_penalty 0.2

SYSTEM """You are JiuZhang-Math, a specialized mathematical reasoning model.
You excel at step-by-step proofs, symbolic computation, and problem solving.
Always show your reasoning and verify your answers.
Use both Chinese and English as appropriate."""
'''
    
    modelfile_path = f"Modelfile.{model_name}"
    Path(modelfile_path).write_text(modelfile, encoding="utf-8")
    
    print(f"  Modelfile created: {modelfile_path}")
    print(f"  Run: ollama create {model_name} -f {modelfile_path}")
    
    # Try to create if ollama is available
    try:
        result = subprocess.run(
            ["ollama", "create", model_name, "-f", modelfile_path],
            capture_output=True, text=True, timeout=300
        )
        if result.returncode == 0:
            print(f"  Ollama model created: {model_name}")
            print(f"  Test with: ollama run {model_name} 'Solve: 3x + 7 = 22'")
            return True
        else:
            print(f"  Ollama create failed: {result.stderr}")
            return False
    except FileNotFoundError:
        print("  Ollama not found. Install from https://ollama.ai")
        return False
    except subprocess.TimeoutExpired:
        print("  Ollama create timed out (model may be large)")
        return False


def _detect_device():
    """Detect available hardware."""
    try:
        import torch
        if torch.backends.mps.is_available():
            return "Apple Silicon (MPS)"
        elif torch.cuda.is_available():
            return f"NVIDIA GPU ({torch.cuda.get_device_name(0)})"
    except ImportError:
        pass
    
    import platform
    if platform.system() == "Darwin" and platform.processor() == "arm":
        return "Apple Silicon (no PyTorch)"
    return "CPU"


def main():
    import argparse
    parser = argparse.ArgumentParser(description="JiuZhang End-to-End Math Model Training")
    parser.add_argument("--step", choices=["prepare", "download", "train", "export", "all"],
                       default="all", help="Which step to run")
    parser.add_argument("--model-path", help="Path to downloaded model (skip download)")
    parser.add_argument("--epochs", type=int, default=3, help="Number of epochs")
    parser.add_argument("--lora-r", type=int, default=16, help="LoRA rank")
    parser.add_argument("--output", default="jiuzhang-math-0.8b", help="Output directory")
    args = parser.parse_args()
    
    # Update module-level config
    global EPOCHS, LORA_R, OUTPUT_DIR
    EPOCHS = args.epochs
    LORA_R = args.lora_r
    OUTPUT_DIR = args.output
    
    print("JiuZhang Math Model Training Pipeline")
    print("Device: " + _detect_device())
    print()
    
    model_path = args.model_path
    
    if args.step in ("prepare", "all"):
        num_samples = step_prepare_data()
        if num_samples == 0:
            print("ERROR: No training data found!")
            sys.exit(1)
    
    if args.step in ("download", "all"):
        if not model_path:
            model_path = step_download_model()
            if not model_path:
                print("ERROR: Model download failed!")
                sys.exit(1)
    
    if args.step in ("train", "all"):
        script_path = step_generate_training_script(model_path)
        print("\nTo start training, run:")
        print("  python " + script_path)
        print("\nTraining will take approximately %d hours on Apple Silicon." % (EPOCHS * 2))
        print("You can monitor progress in the output logs.")
    
    if args.step in ("export", "all"):
        step_export_to_ollama()


if __name__ == "__main__":
    main()
