#!/usr/bin/env python3
"""JiuZhang Math Model Training Script — QLoRA on Qwen3.5-0.8B

Auto-generated by train_math_model_end_to_end.py
"""

import os
import json
import time
from pathlib import Path

os.environ["WANDB_DISABLED"] = "true"

# Detect device
import torch
if torch.backends.mps.is_available():
    device = "mps"
    print("Using Apple Silicon MPS")
elif torch.cuda.is_available():
    device = "cuda"
    print("Using CUDA: " + torch.cuda.get_device_name(0))
else:
    device = "cpu"
    print("Using CPU (will be slow)")

# Apple Silicon (MPS) not supported by unsloth, use standard transformers
HAS_UNSLOTH = False
print("Using standard transformers (unsloth not supported on Apple Silicon)")

from transformers import (
    AutoModelForCausalLM, AutoTokenizer,
    BitsAndBytesConfig, TrainingArguments, Trainer,
    DataCollatorForSeq2Seq,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from datasets import load_dataset

# Configuration
MODEL_PATH = "/Users/fred/.cache/modelscope/hub/models/Qwen/Qwen3___5-0___8B"
DATA_PATH = "jiuzhang_merged_training.jsonl"
OUTPUT_DIR = "jiuzhang-math-0.8b"
MAX_SEQ_LENGTH = 1024
BATCH_SIZE = 1
GRADIENT_ACCUMULATION = 32
EPOCHS = 3
LEARNING_RATE = 0.0002
LORA_R = 16
LORA_ALPHA = 32

print("=" * 60)
print("JiuZhang Math Model Training")
print("=" * 60)
print("Model: " + MODEL_PATH)
print("Data: " + DATA_PATH)
print("Output: " + OUTPUT_DIR)
print("Device: " + device)
print("LoRA r=%d, alpha=%d" % (LORA_R, LORA_ALPHA))
print("Effective batch: %d" % (BATCH_SIZE * GRADIENT_ACCUMULATION))
print("Epochs: %d" % EPOCHS)
print("Learning rate: %s" % LEARNING_RATE)
print("=" * 60)

# Load tokenizer
print("Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# Load model on CPU (MPS training unstable)
print("Loading model on CPU (MPS training unstable)...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_PATH,
    device_map="cpu",
    torch_dtype=torch.float32,
)

# Apply LoRA
print("Applying LoRA adapters...")
model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=False)
lora_config = LoraConfig(
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    lora_dropout=0.05,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj",
                   "gate_proj", "up_proj", "down_proj"],
    bias="none",
    task_type="CAUSAL_LM",
)
model = get_peft_model(model, lora_config)

model.print_trainable_parameters()

# Load and format data
print("Loading training data...")
dataset = load_dataset("json", data_files=DATA_PATH, split="train")
print("Loaded %d samples" % len(dataset))

def tokenize(example):
    messages = example["messages"]
    text = tokenizer.apply_chat_template(messages, tokenize=False)
    tokenized = tokenizer(text, truncation=True, max_length=MAX_SEQ_LENGTH)
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized

dataset = dataset.map(tokenize, remove_columns=dataset.column_names)

# Training arguments
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION,
    warmup_ratio=0.05,
    num_train_epochs=EPOCHS,
    learning_rate=LEARNING_RATE,
    weight_decay=0.01,
    lr_scheduler_type="cosine",
    logging_steps=10,
    save_steps=100,
    save_total_limit=3,
    optim="adamw_torch",
    seed=42,
    report_to="none",
    torch_compile=False,
    dataloader_num_workers=0,
    dataloader_pin_memory=False,
    gradient_checkpointing=False,
    fp16=False,
    bf16=False,
)

# Train
print("Starting training...")
start_time = time.time()

trainer = Trainer(
    model=model,
    train_dataset=dataset,
    args=training_args,
)

trainer.train()

elapsed = time.time() - start_time
print("Training completed in %.1f minutes" % (elapsed/60))

# Save
print("Saving model to " + OUTPUT_DIR + "...")
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

# Export GGUF if unsloth
if HAS_UNSLOTH:
    print("Exporting to GGUF...")
    model.save_pretrained_gguf(OUTPUT_DIR, tokenizer)
    print("GGUF model exported to " + OUTPUT_DIR)

print("=" * 60)
print("Training complete!")
print("Model saved to: " + OUTPUT_DIR)
print("=" * 60)