"""Frontier Research Assistant for JiuZhang.

Integrates all frontier mathematics capabilities:
- Knowledge base access
- Advanced symbolic computation
- Paper reading and summarization
- Advanced visualization
- AI-assisted research
"""

from typing import Optional
from datetime import datetime

from jiuzhang.core.config import Config
from jiuzhang.core.multi_provider_api import MultiProviderClient
from jiuzhang.research.frontier import FrontierMathKB
from jiuzhang.research.advanced_symbolic import AdvancedSymbolicEngine
from jiuzhang.research.paper_reader import PaperReader
from jiuzhang.research.frontier_viz import FrontierVisualizer
from jiuzhang.research.writing_style import FRONTIER_PROMPT, WRITING_PRINCIPLES


class FrontierResearchAssistant:
    """Frontier Mathematics Research Assistant.

    Usage:
        assistant = FrontierResearchAssistant()
        result = assistant.research("朗兰兹纲领")
        print(result)
    """

    def __init__(self, config: Optional[Config] = None):
        self.config = config or Config()
        self.client = MultiProviderClient(self.config)
        self.kb = FrontierMathKB()
        self.symbolic = AdvancedSymbolicEngine(self.config)
        self.paper_reader = PaperReader()
        self.visualizer = FrontierVisualizer()

    def research(
        self,
        query: str,
        language: Optional[str] = None,
        include_papers: bool = True,
        include_visualization: bool = True,
        depth: str = "deep",
    ) -> str:
        """Conduct frontier mathematics research.

        Args:
            query: Research query
            language: Output language
            include_papers: Whether to search papers
            include_visualization: Whether to generate visualizations
            depth: Research depth

        Returns:
            Complete research report
        """
        lang = language or self.config.language
        parts = []

        # Header
        if lang == "zh":
            parts.append(f"# 🔬 前沿数学研究：{query}\n")
            parts.append(
                f"**研究时间**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
            )
            parts.append(f"**研究深度**: {depth}\n")
        else:
            parts.append(f"# 🔬 Frontier Mathematics Research: {query}\n")
            parts.append(
                f"**Research Time**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
            )
            parts.append(f"**Depth**: {depth}\n")

        parts.append("---\n")

        # Step 1: Knowledge base lookup
        kb_result = self._search_knowledge_base(query, lang)
        if kb_result:
            parts.append(kb_result)

        # Step 2: Advanced symbolic computation
        symbolic_result = self.symbolic.compute(query, lang)
        if symbolic_result:
            parts.append(symbolic_result)

        # Step 3: Paper search
        if include_papers:
            papers_result = self._search_papers(query, lang)
            if papers_result:
                parts.append(papers_result)

        # Step 4: AI deep analysis
        ai_result = self._ai_deep_analysis(query, lang, depth)
        if ai_result:
            parts.append(ai_result)

        # Step 5: Visualization suggestions
        if include_visualization:
            viz_result = self._suggest_visualizations(query, lang)
            if viz_result:
                parts.append(viz_result)

        # Footer
        parts.append("\n---\n")
        if lang == "zh":
            parts.append("*本报告由九章 (JiuZhang) 前沿数学研究助手生成*\n")
        else:
            parts.append(
                "*This report was generated by JiuZhang Frontier Mathematics Research Assistant*\n"
            )

        return "\n".join(parts)

    def _search_knowledge_base(self, query: str, language: str) -> str:
        """Search the frontier knowledge base."""
        topics = self.kb.search(query, language)

        if not topics:
            return ""

        parts = []
        if language == "zh":
            parts.append("## 相关前沿领域\n")
            parts.append(
                f"围绕该主题涉及 {len(topics)} 个前沿研究方向，以下逐一介绍。\n"
            )

            for topic in topics[:3]:
                parts.append(f"\n### {topic.name_cn}\n\n")
                parts.append(f"{topic.description_cn}\n\n")

                if topic.key_concepts:
                    concepts_str = "、".join(topic.key_concepts[:5])
                    parts.append(f"该方向的核心概念包括{concepts_str}。\n\n")

                if topic.key_theorems:
                    theorems_str = "、".join(topic.key_theorems[:3])
                    parts.append(f"关键定理有{theorems_str}。\n\n")

                if topic.open_problems:
                    parts.append("当前尚未解决的问题包括：")
                    for problem in topic.open_problems[:3]:
                        parts.append(f"{problem}。")
                    parts.append("\n\n")

                if topic.arxiv_categories:
                    parts.append(f"arXiv 分类：{', '.join(topic.arxiv_categories)}。\n")
        else:
            parts.append("## Related Frontier Areas\n")
            parts.append(
                f"This topic relates to {len(topics)} frontier research areas.\n"
            )

            for topic in topics[:3]:
                parts.append(f"\n### {topic.name}\n\n")
                parts.append(f"{topic.description}\n\n")

                if topic.key_concepts:
                    concepts_str = ", ".join(topic.key_concepts[:5])
                    parts.append(f"Key concepts include {concepts_str}.\n\n")

                if topic.open_problems:
                    parts.append("Open problems include: ")
                    for problem in topic.open_problems[:3]:
                        parts.append(f"{problem}. ")
                    parts.append("\n\n")

        return "\n".join(parts)

    def _search_papers(self, query: str, language: str) -> str:
        """Search for recent papers on the topic."""
        from jiuzhang.research.literature import LiteratureSearcher

        searcher = LiteratureSearcher()

        # Search with frontier-relevant categories
        papers = searcher.search(query, max_results=5)

        if not papers or not papers[0].get("title"):
            return ""

        parts = []
        if language == "zh":
            parts.append("\n## 相关文献\n")
            parts.append(f"共检索到 {len(papers)} 篇相关文献。\n\n")

            for i, paper in enumerate(papers, 1):
                title = paper.get("title", "Unknown")
                authors = paper.get("authors", "Unknown")
                published = paper.get("published", "Unknown")
                summary = paper.get("summary", "No abstract")[:300]
                url = paper.get("url", "")

                parts.append(f"[{i}] {authors}. {title}. {published}.\n")
                if summary:
                    parts.append(f"摘要：{summary}...\n")
                if url:
                    parts.append(f"链接：{url}\n")
                parts.append("\n")
        else:
            parts.append("\n## Related Literature\n")
            parts.append(f"Found {len(papers)} relevant papers.\n\n")

            for i, paper in enumerate(papers, 1):
                title = paper.get("title", "Unknown")
                authors = paper.get("authors", "Unknown")
                published = paper.get("published", "Unknown")
                summary = paper.get("summary", "No abstract")[:300]
                url = paper.get("url", "")

                parts.append(f"[{i}] {authors}. {title}. {published}.\n")
                if summary:
                    parts.append(f"Abstract: {summary}...\n")
                if url:
                    parts.append(f"Link: {url}\n")
                parts.append("\n")

        return "\n".join(parts)

    def _ai_deep_analysis(self, query: str, language: str, depth: str) -> str:
        """Use AI for deep frontier analysis."""
        lang = "中文" if language == "zh" else "English"

        prompt = FRONTIER_PROMPT.format(
            topic=query,
            lang=lang,
            principles=WRITING_PRINCIPLES,
        )

        messages = [{"role": "user", "content": prompt}]
        result = self.client.send_message(messages)
        return result.data if result.success else ""

    def _suggest_visualizations(self, query: str, language: str) -> str:
        """Suggest and generate visualizations for the topic."""
        parts = []
        if language == "zh":
            parts.append("\n## 可视化建议\n")
        else:
            parts.append("\n## Visualization Suggestions\n")

        suggestions = []

        # Check for topics that match visualization types
        if any(
            kw in query
            for kw in ["流形", "manifold", "曲面", "surface", "环面", "torus"]
        ):
            suggestions.append("3D 流形可视化")
        if any(
            kw in query for kw in ["莫比乌斯", "mobius", "不可定向", "non-orientable"]
        ):
            suggestions.append("莫比乌斯带可视化")
        if any(kw in query for kw in ["克莱因", "klein", "拓扑", "topology"]):
            suggestions.append("克莱因瓶可视化")
        if any(
            kw in query for kw in ["向量场", "vector field", "微分方程", "differential"]
        ):
            suggestions.append("向量场可视化")
        if any(
            kw in query
            for kw in ["复分析", "complex", "全纯", "holomorphic", "黎曼", "riemann"]
        ):
            suggestions.append("复函数域着色可视化")
        if any(
            kw in query
            for kw in ["根系", "root system", "李群", "lie", "表示", "representation"]
        ):
            suggestions.append("根系可视化")
        if any(
            kw in query
            for kw in ["分形", "fractal", "曼德博", "mandelbrot", "朱利亚", "julia"]
        ):
            suggestions.append("分形可视化")

        if suggestions:
            if language == "zh":
                parts.append("推荐可视化类型:\n")
                for s in suggestions:
                    parts.append(f"- {s}\n")
            else:
                parts.append("Recommended visualization types:\n")
                for s in suggestions:
                    parts.append(f"- {s}\n")
        else:
            if language == "zh":
                parts.append("该主题适合使用概念图和关系图进行可视化。\n")
            else:
                parts.append(
                    "This topic is suitable for concept maps and relationship diagrams.\n"
                )

        return "\n".join(parts)

    def get_frontier_overview(self, language: str = "zh") -> str:
        """Get an overview of all frontier topics."""
        return self.kb.generate_overview(language)

    def read_paper(self, arxiv_id: str, language: str = "zh") -> str:
        """Read and summarize a specific paper.

        Args:
            arxiv_id: arXiv ID
            language: Output language

        Returns:
            Paper summary
        """
        return self.paper_reader.fetch_and_summarize(arxiv_id, language)

    def generate_visualization(self, viz_type: str, **kwargs) -> Optional[str]:
        """Generate a specific visualization.

        Args:
            viz_type: Visualization type
            **kwargs: Visualization parameters

        Returns:
            Base64 encoded image or None
        """
        viz_methods = {
            "torus": self.visualizer.plot_torus,
            "mobius": self.visualizer.plot_mobius_strip,
            "klein": self.visualizer.plot_klein_bottle,
            "root_system": self.visualizer.plot_root_system,
            "fractal": self.visualizer.plot_fractal,
            "complex": self.visualizer.plot_complex_function,
            "vector_field": self.visualizer.plot_vector_field,
            "3d_surface": self.visualizer.plot_3d_surface,
        }

        method = viz_methods.get(viz_type)
        if method:
            return method(**kwargs)
        return None
