"""Code Interpreter for JiuZhang Math Reasoning.

Allows the model to generate and execute Python/SymPy code to solve math problems.
This is crucial for local models which often struggle with arithmetic and symbolic manipulation.

Features:
  - Safe execution sandbox
  - SymPy integration
  - Output capture
  - Error handling
"""

import re
import sys
import io
import ast
import types
from typing import Dict, List, Optional, Tuple, Any
from dataclasses import dataclass

import sympy as sp
from sympy import (
    symbols, Symbol, Rational, pi, E, I, oo, sqrt, sin, cos, tan,
    exp, log, diff, integrate, solve, simplify, factor, expand,
    limit, series, Matrix, factorial, gcd, isprime, primerange,
    Eq, Ne, Lt, Gt, Le, Ge,
)


@dataclass
class CodeExecutionResult:
    success: bool
    output: str
    error: Optional[str] = None
    code: str = ""
    execution_time: float = 0.0


class SafeMathEnvironment:
    """A restricted environment for executing math code."""

    def __init__(self):
        self.globals = {
            '__builtins__': {
                'len': len,
                'range': range,
                'print': print,
                'int': int,
                'float': float,
                'str': str,
                'list': list,
                'dict': dict,
                'tuple': tuple,
                'set': set,
                'bool': bool,
                'abs': abs,
                'min': min,
                'max': max,
                'sum': sum,
                'pow': pow,
                'round': round,
                'True': True,
                'False': False,
                'None': None,
            },
            # SymPy symbols
            'x': symbols('x'),
            'y': symbols('y'),
            'z': symbols('z'),
            'n': symbols('n', integer=True),
            'k': symbols('k', integer=True),
            'i': symbols('i', integer=True),
            't': symbols('t'),
            # SymPy functions and constants
            'symbols': symbols,
            'Symbol': Symbol,
            'Rational': Rational,
            'pi': pi,
            'E': E,
            'I': I,
            'oo': oo,
            'sqrt': sqrt,
            'sin': sin,
            'cos': cos,
            'tan': tan,
            'exp': exp,
            'log': log,
            'diff': diff,
            'integrate': integrate,
            'solve': solve,
            'simplify': simplify,
            'factor': factor,
            'expand': expand,
            'limit': limit,
            'series': series,
            'Matrix': Matrix,
            'factorial': factorial,
            'gcd': gcd,
            'isprime': isprime,
            'primerange': primerange,
            'Eq': Eq,
            'Ne': Ne,
            'Lt': Lt,
            'Gt': Gt,
            'Le': Le,
            'Ge': Ge,
            'latex': sp.latex,
            'N': sp.N,
            'evalf': lambda expr: expr.evalf(),
        }

    def execute(self, code: str, timeout: int = 5) -> CodeExecutionResult:
        """Execute code in the safe environment."""
        # Security check: forbid dangerous imports and functions
        if self._is_unsafe(code):
            return CodeExecutionResult(
                success=False,
                output="",
                error="Security violation: unsafe code detected",
                code=code,
            )

        # Capture stdout
        old_stdout = sys.stdout
        redirected_output = io.StringIO()
        sys.stdout = redirected_output

        try:
            # Execute the code
            exec(code, self.globals)
            output = redirected_output.getvalue()
            return CodeExecutionResult(
                success=True,
                output=output,
                code=code,
            )
        except Exception as e:
            return CodeExecutionResult(
                success=False,
                output=redirected_output.getvalue(),
                error=str(e),
                code=code,
            )
        finally:
            sys.stdout = old_stdout

    def _is_unsafe(self, code: str) -> bool:
        """Check if code contains unsafe patterns."""
        unsafe_patterns = [
            'import os', 'import sys', 'import subprocess', 'import shutil',
            '__import__', 'open(', 'eval(', 'exec(', 'compile(',
            'globals()', 'locals()', 'vars()', 'dir(',
            'getattr', 'setattr', 'delattr',
            'breakpoint', 'input(',
        ]
        code_lower = code.lower()
        return any(pattern in code_lower for pattern in unsafe_patterns)


class CodeInterpreter:
    """Interprets and executes math code generated by the model."""

    def __init__(self):
        self.env = SafeMathEnvironment()

    def execute_code(self, code: str) -> CodeExecutionResult:
        """Execute a code block."""
        return self.env.execute(code)

    def extract_code_blocks(self, text: str) -> List[str]:
        """Extract Python code blocks from text."""
        # Match ```python ... ``` or ``` ... ```
        pattern = r'```(?:python)?\s*(.*?)```'
        matches = re.findall(pattern, text, re.DOTALL)
        return [m.strip() for m in matches if m.strip()]

    def solve_with_code(self, problem: str, model_response: str) -> Tuple[bool, str, str]:
        """
        Solve a problem using code extracted from model response.
        
        Returns: (success, result_text, code_used)
        """
        code_blocks = self.extract_code_blocks(model_response)
        if not code_blocks:
            return False, "No code blocks found in response", ""
        
        # Try executing each code block until one succeeds
        last_error = ""
        for code in code_blocks:
            result = self.execute_code(code)
            if result.success:
                return True, result.output, code
            last_error = result.error
        
        return False, f"Execution failed: {last_error}", code_blocks[-1] if code_blocks else ""


def main():
    import argparse
    parser = argparse.ArgumentParser(description="JiuZhang Code Interpreter")
    parser.add_argument("code", nargs="?", help="Code to execute")
    parser.add_argument("--file", help="Read code from file")
    args = parser.parse_args()

    interpreter = CodeInterpreter()

    if args.file:
        with open(args.file, 'r') as f:
            code = f.read()
    elif args.code:
        code = args.code
    else:
        code = """
x = symbols('x')
f = x**3 + 2*x**2 - 5*x + 1
f_prime = diff(f, x)
print(f"f'(x) = {f_prime}")
"""

    print(f"Executing code:\n{code}\n{'='*40}")
    result = interpreter.execute_code(code)
    
    if result.success:
        print(f"Output:\n{result.output}")
    else:
        print(f"Error: {result.error}")


if __name__ == "__main__":
    main()