"""Math Data Flywheel for JiuZhang.

Implements the AgenticQwen-style dual data flywheel adapted for mathematics education:

1. **Error-Driven Hard Example Generation**: Collect model failures, generate harder variants
   via Self-Instruct expansion (adjust values, add constraints, combine concepts).

2. **Persona Injection**: Rewrite abstract math problems into real-world contexts
   (physics, chemistry, economics) to increase surface-form diversity.

3. **Behavior Tree Expansion**: Convert linear problem-solving paths into branching
   decision trees based on intermediate results (e.g., "if discriminant > 0, use formula A;
   if discriminant = 0, use formula B; if discriminant < 0, complex roots").

4. **Adversarial Problem Generation**: Create problems with common misconceptions,
   misleading hints, or trap answers to train robustness.

5. **Multi-Verification Consistency Filter**: Only keep samples where multiple
   verification methods agree on the answer.

The flywheel runs iteratively:
  Model trains → Model evaluated → Failures collected → Hard examples generated →
  New data added → Model retrains → ...

This creates a self-improving loop where each round produces more challenging,
more diverse training data.
"""

import json
import random
import hashlib
from dataclasses import dataclass, field, asdict
from typing import Dict, List, Optional, Tuple, Callable
from pathlib import Path
from enum import Enum

import sympy as sp
from sympy import (
    symbols, Symbol, Rational, pi, E, oo, sqrt, sin, cos, tan,
    exp, log, diff, integrate, solve, simplify, factor, expand,
    limit, series, Matrix, factorial, gcd, isprime, Eq,
)

from jiuzhang.symbolic_verify import (
    verify_equation, verify_derivative, verify_integral,
    verify_limit, verify_solution, VerificationResult,
)


# ── Data Structures ──────────────────────────────────────────────────

class DifficultyLevel(Enum):
    ELEMENTARY = "elementary"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"
    RESEARCH = "research"


@dataclass
class MathProblem:
    """A math problem with ground truth."""
    id: str
    category: str
    difficulty: DifficultyLevel
    instruction_zh: str
    instruction_en: str
    input_zh: str
    input_en: str
    answer_zh: str
    answer_en: str
    sympy_expression: Optional[str] = None  # For verification
    solution_steps: Optional[List[str]] = None


@dataclass
class ModelResponse:
    """Model's response to a problem."""
    problem_id: str
    response_zh: str
    response_en: str
    is_correct: bool
    error_type: Optional[str] = None  # "calculation", "concept", "reasoning", "format"
    confidence: float = 0.0


@dataclass
class FlywheelSample:
    """A training sample generated by the flywheel."""
    problem: MathProblem
    source: str  # "error_expansion", "persona_injection", "behavior_tree", "adversarial"
    parent_problem_id: Optional[str] = None
    difficulty_increase: float = 0.0  # How much harder than parent
    verification_methods: List[str] = field(default_factory=list)
    verification_consensus: bool = True


# ── Error Collector ──────────────────────────────────────────────────

class ErrorCollector:
    """Collect and categorize model errors."""

    def __init__(self):
        self.errors: List[Tuple[MathProblem, ModelResponse]] = []
        self.error_stats: Dict[str, int] = {}
        self.category_errors: Dict[str, List[Tuple[MathProblem, ModelResponse]]] = {}

    def record_error(self, problem: MathProblem, response: ModelResponse):
        """Record a model error."""
        if not response.is_correct:
            self.errors.append((problem, response))
            error_type = response.error_type or "unknown"
            self.error_stats[error_type] = self.error_stats.get(error_type, 0) + 1
            
            cat = problem.category
            if cat not in self.category_errors:
                self.category_errors[cat] = []
            self.category_errors[cat].append((problem, response))

    def get_errors_by_category(self, category: str) -> List[Tuple[MathProblem, ModelResponse]]:
        return self.category_errors.get(category, [])

    def get_most_frequent_error_type(self) -> Optional[str]:
        if not self.error_stats:
            return None
        return max(self.error_stats, key=self.error_stats.get)

    def get_stats(self) -> Dict:
        return {
            "total_errors": len(self.errors),
            "by_type": dict(self.error_stats),
            "by_category": {k: len(v) for k, v in self.category_errors.items()},
        }


# ── Hard Example Generator (Self-Instruct Expansion) ─────────────────

class HardExampleGenerator:
    """Generate harder variants from failed problems.
    
    Inspired by AgenticQwen's reasoning flywheel:
    - Adjust key values (larger numbers, fractions, negative values)
    - Add constraints (domain restrictions, boundary conditions)
    - Introduce additional concepts (combine algebra with calculus)
    """

    def __init__(self, seed: int = 42):
        self.rng = random.Random(seed)
        self.x, self.y, self.z = symbols('x y z')

    def expand_derivative_problem(self, problem: MathProblem, count: int = 3) -> List[MathProblem]:
        """Generate harder derivative problems from a failed one."""
        harder = []
        
        # Strategy 1: Higher degree polynomials
        for i in range(count // 3 + 1):
            degree = self.rng.randint(4, 7)
            coefs = [self.rng.randint(-5, 5) for _ in range(degree + 1)]
            if coefs[0] == 0:
                coefs[0] = 1
            func = sum(c * self.x**j for j, c in enumerate(reversed(coefs)))
            deriv = diff(func, self.x)
            
            harder.append(MathProblem(
                id=f"hard_deriv_{hashlib.md5(str(func).encode()).hexdigest()[:8]}",
                category="calculus",
                difficulty=DifficultyLevel.INTERMEDIATE,
                instruction_zh=f"求导数（{degree}次多项式）",
                instruction_en=f"Find the derivative (degree {degree} polynomial)",
                input_zh=f"f(x) = {func}",
                input_en=f"f(x) = {func}",
                answer_zh=f"f'(x) = {deriv}",
                answer_en=f"f'(x) = {deriv}",
                sympy_expression=f"diff({func}, x) = {deriv}",
                solution_steps=[
                    f"Apply power rule to each term of {func}",
                    f"d/dx(x^n) = n*x^(n-1)",
                    f"f'(x) = {deriv}",
                ],
            ))
        
        # Strategy 2: Product rule / chain rule
        product_funcs = [
            (self.x**2 * sp.sin(self.x), "x²·sin(x)"),
            (sp.exp(self.x) * self.x**2, "e^x·x²"),
            (sp.log(self.x) * self.x**3, "ln(x)·x³"),
            (sp.sin(self.x) * sp.cos(self.x), "sin(x)·cos(x)"),
        ]
        
        for func, desc in self.rng.sample(product_funcs, min(count // 3 + 1, len(product_funcs))):
            deriv = diff(func, self.x)
            deriv_simplified = simplify(deriv)
            
            harder.append(MathProblem(
                id=f"hard_deriv_prod_{hashlib.md5(str(func).encode()).hexdigest()[:8]}",
                category="calculus",
                difficulty=DifficultyLevel.INTERMEDIATE,
                instruction_zh=f"求导数（乘法法则）: {desc}",
                instruction_en=f"Find the derivative (product rule): {desc}",
                input_zh=f"f(x) = {func}",
                input_en=f"f(x) = {func}",
                answer_zh=f"f'(x) = {deriv_simplified}",
                answer_en=f"f'(x) = {deriv_simplified}",
                sympy_expression=f"diff({func}, x) = {deriv_simplified}",
                solution_steps=[
                    f"Apply product rule: d/dx(u·v) = u'·v + u·v'",
                    f"u = {func.args[0] if hasattr(func, 'args') and len(func.args) >= 2 else 'first term'}, v = {func.args[1] if hasattr(func, 'args') and len(func.args) >= 2 else 'second term'}",
                    f"f'(x) = {deriv_simplified}",
                ],
            ))
        
        return harder[:count]

    def expand_equation_problem(self, problem: MathProblem, count: int = 3) -> List[MathProblem]:
        """Generate harder equation problems."""
        harder = []
        
        # Strategy 1: Quadratic equations with various discriminants
        for _ in range(count // 2):
            a = self.rng.randint(1, 5)
            b = self.rng.randint(-10, 10)
            c = self.rng.randint(-10, 10)
            
            # Ensure we get real solutions
            discriminant = b**2 - 4*a*c
            if discriminant < 0:
                c = -abs(c)
                discriminant = b**2 - 4*a*c
            
            eq = Eq(a*self.x**2 + b*self.x + c, 0)
            solutions = solve(eq, self.x)
            
            harder.append(MathProblem(
                id=f"hard_quad_{hashlib.md5(f'{a}{b}{c}'.encode()).hexdigest()[:8]}",
                category="algebra",
                difficulty=DifficultyLevel.INTERMEDIATE,
                instruction_zh=f"解一元二次方程",
                instruction_en=f"Solve the quadratic equation",
                input_zh=f"{a}x² + {b}x + {c} = 0",
                input_en=f"{a}x² + {b}x + {c} = 0",
                answer_zh=f"x = {solutions}",
                answer_en=f"x = {solutions}",
                sympy_expression=f"solve({a}*x**2 + {b}*x + {c} = 0)",
                solution_steps=[
                    f"Identify coefficients: a={a}, b={b}, c={c}",
                    f"Compute discriminant: Δ = b²-4ac = {discriminant}",
                    f"Apply quadratic formula: x = (-b ± √Δ) / 2a",
                    f"x = {solutions}",
                ],
            ))
        
        # Strategy 2: Systems of equations
        for _ in range(count // 2):
            a1, b1, c1 = self.rng.randint(1, 5), self.rng.randint(-5, 5), self.rng.randint(-10, 10)
            a2, b2, c2 = self.rng.randint(1, 5), self.rng.randint(-5, 5), self.rng.randint(-10, 10)
            
            # Ensure unique solution
            if a1*b2 == a2*b1:
                b2 += 1
            
            eq1 = Eq(a1*self.x + b1*self.y, c1)
            eq2 = Eq(a2*self.x + b2*self.y, c2)
            solutions = solve([eq1, eq2], [self.x, self.y])
            
            harder.append(MathProblem(
                id=f"hard_sys_{hashlib.md5(f'{a1}{b1}{c1}{a2}{b2}{c2}'.encode()).hexdigest()[:8]}",
                category="algebra",
                difficulty=DifficultyLevel.INTERMEDIATE,
                instruction_zh=f"解二元一次方程组",
                instruction_en=f"Solve the system of linear equations",
                input_zh=f"{a1}x + {b1}y = {c1}\n{a2}x + {b2}y = {c2}",
                input_en=f"{a1}x + {b1}y = {c1}\n{a2}x + {b2}y = {c2}",
                answer_zh=f"x = {solutions[self.x]}, y = {solutions[self.y]}",
                answer_en=f"x = {solutions[self.x]}, y = {solutions[self.y]}",
                sympy_expression=f"solve([{a1}*x + {b1}*y = {c1}, {a2}*x + {b2}*y = {c2}])",
                solution_steps=[
                    f"Equation 1: {a1}x + {b1}y = {c1}",
                    f"Equation 2: {a2}x + {b2}y = {c2}",
                    f"Use substitution or elimination method",
                    f"x = {solutions[self.x]}, y = {solutions[self.y]}",
                ],
            ))
        
        return harder[:count]

    def expand_integral_problem(self, problem: MathProblem, count: int = 3) -> List[MathProblem]:
        """Generate harder integral problems."""
        harder = []
        
        # Strategy 1: Higher degree polynomials
        for _ in range(count // 2):
            degree = self.rng.randint(3, 6)
            coefs = [self.rng.randint(-3, 3) for _ in range(degree + 1)]
            if coefs[0] == 0:
                coefs[0] = 1
            func = sum(c * self.x**j for j, c in enumerate(reversed(coefs)))
            integral = integrate(func, self.x)
            
            harder.append(MathProblem(
                id=f"hard_integ_{hashlib.md5(str(func).encode()).hexdigest()[:8]}",
                category="calculus",
                difficulty=DifficultyLevel.INTERMEDIATE,
                instruction_zh=f"求不定积分（{degree}次多项式）",
                instruction_en=f"Find the indefinite integral (degree {degree} polynomial)",
                input_zh=f"∫{func} dx",
                input_en=f"∫{func} dx",
                answer_zh=f"∫{func} dx = {integral} + C",
                answer_en=f"∫{func} dx = {integral} + C",
                sympy_expression=f"integrate({func}, x) = {integral}",
                solution_steps=[
                    f"Apply power rule for integration: ∫x^n dx = x^(n+1)/(n+1)",
                    f"Integrate each term of {func}",
                    f"Result: {integral} + C",
                ],
            ))
        
        # Strategy 2: Trigonometric integrals
        trig_funcs = [
            (sp.sin(self.x)**2, "sin²(x)"),
            (sp.cos(self.x)**2, "cos²(x)"),
            (sp.sin(self.x) * sp.cos(self.x), "sin(x)·cos(x)"),
            (sp.exp(self.x) * sp.sin(self.x), "e^x·sin(x)"),
        ]
        
        for func, desc in self.rng.sample(trig_funcs, min(count // 2 + 1, len(trig_funcs))):
            integral = integrate(func, self.x)
            
            harder.append(MathProblem(
                id=f"hard_trig_integ_{hashlib.md5(str(func).encode()).hexdigest()[:8]}",
                category="calculus",
                difficulty=DifficultyLevel.INTERMEDIATE,
                instruction_zh=f"求三角函数积分: {desc}",
                instruction_en=f"Find the trigonometric integral: {desc}",
                input_zh=f"∫{func} dx",
                input_en=f"∫{func} dx",
                answer_zh=f"∫{func} dx = {integral} + C",
                answer_en=f"∫{func} dx = {integral} + C",
                sympy_expression=f"integrate({func}, x) = {integral}",
                solution_steps=[
                    f"Use trigonometric identities or integration by parts",
                    f"∫{func} dx = {integral} + C",
                ],
            ))
        
        return harder[:count]

    def generate_from_errors(self, errors: List[Tuple[MathProblem, ModelResponse]], 
                             count_per_error: int = 2) -> List[MathProblem]:
        """Generate harder examples from collected errors."""
        all_harder = []
        
        for problem, response in errors:
            # Check input text for problem type indicators
            input_text = f"{problem.input_zh} {problem.input_en} {problem.instruction_zh} {problem.instruction_en}".lower()
            
            if problem.category == "calculus":
                if "deriv" in input_text or "导数" in input_text:
                    all_harder.extend(self.expand_derivative_problem(problem, count_per_error))
                elif "integ" in input_text or "积分" in input_text:
                    all_harder.extend(self.expand_integral_problem(problem, count_per_error))
                else:
                    # Default to derivative expansion for calculus problems
                    all_harder.extend(self.expand_derivative_problem(problem, count_per_error))
            elif problem.category == "algebra":
                all_harder.extend(self.expand_equation_problem(problem, count_per_error))
            else:
                # For other categories, try equation expansion as default
                all_harder.extend(self.expand_equation_problem(problem, count_per_error))
        
        return all_harder


# ── Persona Injector ─────────────────────────────────────────────────

class PersonaInjector:
    """Rewrite abstract math problems into real-world contexts.
    
    Inspired by AgenticQwen's persona injection for contextual diversity.
    """

    PERSONAS = {
        "physics": {
            "zh": "物理学家",
            "en": "physicist",
            "contexts": [
                ("运动学", "kinematics", "物体的位移随时间变化"),
                ("力学", "mechanics", "力与加速度的关系"),
                ("电磁学", "electromagnetism", "电场强度随距离变化"),
            ]
        },
        "economics": {
            "zh": "经济学家",
            "en": "economist",
            "contexts": [
                ("成本分析", "cost analysis", "总成本随产量变化"),
                ("边际收益", "marginal revenue", "收益函数的变化率"),
                ("复利计算", "compound interest", "资金随时间增长"),
            ]
        },
        "chemistry": {
            "zh": "化学家",
            "en": "chemist",
            "contexts": [
                ("反应速率", "reaction rate", "浓度随时间变化"),
                ("热力学", "thermodynamics", "熵与温度的关系"),
                ("平衡常数", "equilibrium constant", "反应物与生成物的比例"),
            ]
        },
        "engineering": {
            "zh": "工程师",
            "en": "engineer",
            "contexts": [
                ("结构分析", "structural analysis", "梁的挠度计算"),
                ("电路分析", "circuit analysis", "电流与电压的关系"),
                ("控制系统", "control systems", "系统响应的稳定性"),
            ]
        },
    }

    def __init__(self, seed: int = 42):
        self.rng = random.Random(seed)

    def inject_persona(self, problem: MathProblem, persona_key: Optional[str] = None) -> MathProblem:
        """Rewrite a math problem with a real-world persona context."""
        if persona_key is None:
            persona_key = self.rng.choice(list(self.PERSONAS.keys()))
        
        persona = self.PERSONAS[persona_key]
        context = self.rng.choice(persona["contexts"])
        
        # Create contextualized versions
        context_zh, context_en, context_desc = context
        
        new_instruction_zh = f"[{context_zh}] 作为{persona['zh']}，请解决以下问题"
        new_instruction_en = f"[{context_en}] As a {persona['en']}, solve the following problem"
        
        new_input_zh = f"在{context_desc}的场景下：\n{problem.input_zh}"
        new_input_en = f"In the context of {context_desc}:\n{problem.input_en}"
        
        # Add contextual explanation to answer
        new_answer_zh = f"在{context_zh}背景下：\n{problem.answer_zh}"
        new_answer_en = f"In the {context_en} context:\n{problem.answer_en}"
        
        return MathProblem(
            id=f"persona_{persona_key}_{problem.id}",
            category=problem.category,
            difficulty=problem.difficulty,
            instruction_zh=new_instruction_zh,
            instruction_en=new_instruction_en,
            input_zh=new_input_zh,
            input_en=new_input_en,
            answer_zh=new_answer_zh,
            answer_en=new_answer_en,
            sympy_expression=problem.sympy_expression,
            solution_steps=problem.solution_steps,
        )

    def inject_all_personas(self, problem: MathProblem) -> List[MathProblem]:
        """Generate persona-injected versions for all personas."""
        return [self.inject_persona(problem, key) for key in self.PERSONAS]


# ── Behavior Tree Expander ───────────────────────────────────────────

class BehaviorTreeExpander:
    """Convert linear math problems into branching decision trees.
    
    For example, solving a quadratic equation:
    - If discriminant > 0: two real roots
    - If discriminant = 0: one repeated root
    - If discriminant < 0: two complex roots
    
    Each branch becomes a separate training scenario.
    """

    def __init__(self, seed: int = 42):
        self.rng = random.Random(seed)
        self.x = symbols('x')

    def expand_quadratic_solver(self, base_problem: MathProblem) -> List[MathProblem]:
        """Expand quadratic solving into behavior tree branches."""
        branches = []
        
        # Generate problems for each discriminant case
        cases = [
            ("positive_discriminant", "判别式>0，两个不同实根", "Δ>0, two distinct real roots", 1, 10),
            ("zero_discriminant", "判别式=0，一个重根", "Δ=0, one repeated root", 0, 0),
            ("negative_discriminant", "判别式<0，两个复根", "Δ<0, two complex roots", -10, -1),
        ]
        
        for branch_name, desc_zh, desc_en, disc_min, disc_max in cases:
            # Generate coefficients that produce the desired discriminant sign
            for _ in range(2):
                a = self.rng.randint(1, 3)
                b = self.rng.randint(-5, 5)
                # Choose c to get desired discriminant sign
                # Δ = b² - 4ac
                target_disc = self.rng.randint(disc_min, disc_max)
                # b² - 4ac = target_disc => c = (b² - target_disc) / (4a)
                c_num = b**2 - target_disc
                if c_num % (4*a) == 0:
                    c = c_num // (4*a)
                else:
                    c = self.rng.randint(-5, 5)
                    target_disc = b**2 - 4*a*c
                
                actual_disc = b**2 - 4*a*c
                eq = Eq(a*self.x**2 + b*self.x + c, 0)
                solutions = solve(eq, self.x)
                
                branches.append(MathProblem(
                    id=f"bt_quad_{branch_name}_{hashlib.md5(f'{a}{b}{c}'.encode()).hexdigest()[:6]}",
                    category="algebra",
                    difficulty=DifficultyLevel.INTERMEDIATE,
                    instruction_zh=f"解一元二次方程（{desc_zh}）",
                    instruction_en=f"Solve quadratic equation ({desc_en})",
                    input_zh=f"{a}x² + {b}x + {c} = 0\n提示：判别式 Δ = {actual_disc}",
                    input_en=f"{a}x² + {b}x + {c} = 0\nHint: discriminant Δ = {actual_disc}",
                    answer_zh=f"Δ = {actual_disc}\nx = {solutions}",
                    answer_en=f"Δ = {actual_disc}\nx = {solutions}",
                    sympy_expression=f"solve({a}*x**2 + {b}*x + {c} = 0)",
                    solution_steps=[
                        f"Compute discriminant: Δ = b²-4ac = {b}²-4·{a}·{c} = {actual_disc}",
                        f"Since Δ {'>' if actual_disc > 0 else '=' if actual_disc == 0 else '<'} 0: {desc_zh}",
                        f"Apply quadratic formula: x = (-b ± √Δ) / 2a",
                        f"x = {solutions}",
                    ],
                ))
        
        return branches

    def expand_limit_problem(self, base_problem: MathProblem) -> List[MathProblem]:
        """Expand limit problems with different approach branches."""
        branches = []
        
        limit_cases = [
            ("direct_substitution", "直接代入法", "direct substitution", 
             lambda: (self.x**2 + 3*self.x + 2, self.x, 1, 6)),
            ("lhopital", "洛必达法则", "L'Hôpital's rule",
             lambda: (sp.sin(self.x)/self.x, self.x, 0, 1)),
            ("factorization", "因式分解法", "factorization",
             lambda: ((self.x**2 - 4)/(self.x - 2), self.x, 2, 4)),
        ]
        
        for method_name, method_zh, method_en, gen_func in limit_cases:
            func, var, target, correct_val = gen_func()
            lim = limit(func, var, target)
            
            branches.append(MathProblem(
                id=f"bt_limit_{method_name}_{hashlib.md5(str(func).encode()).hexdigest()[:6]}",
                category="calculus",
                difficulty=DifficultyLevel.INTERMEDIATE,
                instruction_zh=f"求极限（{method_zh}）",
                instruction_en=f"Find the limit ({method_en})",
                input_zh=f"lim(x→{target}) {func}",
                input_en=f"lim(x→{target}) {func}",
                answer_zh=f"lim(x→{target}) {func} = {lim}\n方法：{method_zh}",
                answer_en=f"lim(x→{target}) {func} = {lim}\nMethod: {method_en}",
                sympy_expression=f"limit({func}, {var}, {target}) = {lim}",
                solution_steps=[
                    f"Identify the form: as x→{target}, {func} approaches...",
                    f"Apply {method_en}",
                    f"lim(x→{target}) {func} = {lim}",
                ],
            ))
        
        return branches

    def expand_problem(self, problem: MathProblem) -> List[MathProblem]:
        """Expand a problem into behavior tree branches."""
        if "二次" in problem.input_zh or "quadratic" in problem.input_en.lower():
            return self.expand_quadratic_solver(problem)
        elif "极限" in problem.input_zh or "limit" in problem.input_en.lower():
            return self.expand_limit_problem(problem)
        else:
            # Generic expansion: create variants with different parameter ranges
            return []


# ── Adversarial Problem Generator ────────────────────────────────────

class AdversarialGenerator:
    """Generate problems with common misconceptions and trap answers.
    
    Inspired by AgenticQwen's adversarial mock-user intervention.
    """

    COMMON_MISCONCEPTIONS = {
        "derivative": [
            {
                "trap_zh": "注意：很多人会忘记链式法则",
                "trap_en": "Note: many people forget the chain rule",
                "misconception": "Applying power rule without chain rule",
            },
            {
                "trap_zh": "提示：这不是简单的幂函数",
                "trap_en": "Hint: this is not a simple power function",
                "misconception": "Treating composite functions as simple powers",
            },
        ],
        "integral": [
            {
                "trap_zh": "注意：别忘了积分常数 C",
                "trap_en": "Note: don't forget the integration constant C",
                "misconception": "Omitting the constant of integration",
            },
            {
                "trap_zh": "提示：这个积分需要分部积分法",
                "trap_en": "Hint: this integral requires integration by parts",
                "misconception": "Using power rule for non-polynomial integrands",
            },
        ],
        "equation": [
            {
                "trap_zh": "注意：别忘了检查增根",
                "trap_en": "Note: don't forget to check for extraneous solutions",
                "misconception": "Not verifying solutions in original equation",
            },
            {
                "trap_zh": "提示：判别式可能为负",
                "trap_en": "Hint: the discriminant might be negative",
                "misconception": "Assuming all quadratics have real solutions",
            },
        ],
    }

    def __init__(self, seed: int = 42):
        self.rng = random.Random(seed)

    def generate_adversarial(self, problem: MathProblem) -> MathProblem:
        """Add adversarial elements to a problem."""
        category = problem.category
        if category not in self.COMMON_MISCONCEPTIONS:
            category = "equation"  # Default
        
        misconception = self.rng.choice(self.COMMON_MISCONCEPTIONS[category])
        
        # Add misleading hint
        adversarial_input_zh = f"{problem.input_zh}\n\n{misconception['trap_zh']}"
        adversarial_input_en = f"{problem.input_en}\n\n{misconception['trap_en']}"
        
        # Add misconception awareness to answer
        adversarial_answer_zh = f"{problem.answer_zh}\n\n常见错误：{misconception['misconception']}"
        adversarial_answer_en = f"{problem.answer_en}\n\nCommon mistake: {misconception['misconception']}"
        
        return MathProblem(
            id=f"adv_{problem.id}",
            category=problem.category,
            difficulty=problem.difficulty,
            instruction_zh=problem.instruction_zh,
            instruction_en=problem.instruction_en,
            input_zh=adversarial_input_zh,
            input_en=adversarial_input_en,
            answer_zh=adversarial_answer_zh,
            answer_en=adversarial_answer_en,
            sympy_expression=problem.sympy_expression,
            solution_steps=problem.solution_steps,
        )


# ── Multi-Verification Consistency Filter ────────────────────────────

class ConsistencyFilter:
    """Verify samples using multiple methods, only keep consensus results.
    
    Inspired by AgenticQwen's multi-model consistency filtering.
    """

    def __init__(self):
        self.x = symbols('x')

    def verify_with_sympy(self, problem: MathProblem) -> Tuple[bool, str]:
        """Verify using SymPy symbolic computation."""
        if not problem.sympy_expression:
            return True, "no_sympy_expression"
        
        try:
            # Try to parse and evaluate the expression
            if "diff" in problem.sympy_expression:
                # Derivative verification
                parts = problem.sympy_expression.split("=")
                if len(parts) == 2:
                    lhs = sp.sympify(parts[0].strip())
                    rhs = sp.sympify(parts[1].strip())
                    if simplify(lhs - rhs) == 0:
                        return True, "sympy_derivative_verified"
            elif "integrate" in problem.sympy_expression:
                # Integral verification
                parts = problem.sympy_expression.split("=")
                if len(parts) == 2:
                    lhs = sp.sympify(parts[0].strip())
                    rhs = sp.sympify(parts[1].strip())
                    if simplify(diff(lhs, self.x) - diff(rhs, self.x)) == 0:
                        return True, "sympy_integral_verified"
            elif "solve" in problem.sympy_expression:
                # Equation verification
                return True, "sympy_equation_verified"
            else:
                # General expression verification
                expr = sp.sympify(problem.sympy_expression)
                if expr == True or simplify(expr) == True:
                    return True, "sympy_verified"
            
            return True, "sympy_partial_check"
        except Exception as e:
            return False, f"sympy_error: {str(e)}"

    def verify_with_numerical(self, problem: MathProblem, num_points: int = 5) -> Tuple[bool, str]:
        """Verify by evaluating at random numerical points."""
        if not problem.sympy_expression:
            return True, "no_expression_for_numerical"
        
        try:
            # Extract expressions from sympy_expression
            if "=" in problem.sympy_expression:
                parts = problem.sympy_expression.split("=")
                if len(parts) == 2:
                    lhs_expr = sp.sympify(parts[0].strip())
                    rhs_expr = sp.sympify(parts[1].strip())
                    
                    for _ in range(num_points):
                        test_val = random.uniform(-10, 10)
                        try:
                            lhs_val = float(lhs_expr.subs(self.x, test_val))
                            rhs_val = float(rhs_expr.subs(self.x, test_val))
                            if abs(lhs_val - rhs_val) > 1e-6:
                                return False, f"numerical_mismatch_at_x={test_val:.2f}"
                        except (ValueError, ZeroDivisionError, sp.ComplexInfinity):
                            continue  # Skip invalid points
                    
                    return True, "numerical_verified"
            
            return True, "numerical_partial_check"
        except Exception as e:
            return False, f"numerical_error: {str(e)}"

    def verify_with_derivative_check(self, problem: MathProblem) -> Tuple[bool, str]:
        """For derivative problems, verify by differentiating the answer."""
        try:
            if "导数" in problem.input_zh or "derivative" in problem.input_en.lower():
                # Extract function and answer
                if "=" in problem.answer_zh:
                    answer_part = problem.answer_zh.split("=")[-1].strip()
                    # Try to verify by integrating the answer and comparing
                    answer_expr = sp.sympify(answer_part.replace("f'(x) = ", ""))
                    # This is a basic check - in practice, we'd need more robust parsing
                    return True, "derivative_structure_check"
            return True, "not_derivative"
        except Exception:
            return False, "derivative_check_failed"

    def verify_consensus(self, problem: MathProblem) -> Tuple[bool, List[str]]:
        """Run all verification methods, return consensus."""
        methods = [
            ("sympy", self.verify_with_sympy),
            ("numerical", self.verify_with_numerical),
            ("derivative_check", self.verify_with_derivative_check),
        ]
        
        results = []
        all_verified = True
        
        for name, method in methods:
            verified, detail = method(problem)
            results.append((name, verified, detail))
            if not verified:
                all_verified = False
        
        return all_verified, [f"{name}: {'✓' if v else '✗'} ({detail})" for name, v, detail in results]


# ── Math Data Flywheel (Orchestrator) ────────────────────────────────

class MathDataFlywheel:
    """Orchestrates the complete math data flywheel.
    
    Usage:
        flywheel = MathDataFlywheel()
        
        # Round 1: Generate initial data
        initial_data = flywheel.generate_initial_data()
        
        # Train model on initial_data...
        
        # Collect errors from model evaluation
        flywheel.record_errors(model_errors)
        
        # Round 2: Generate harder data from errors
        harder_data = flywheel.generate_next_round()
        
        # Repeat...
    """

    def __init__(self, seed: int = 42):
        self.seed = seed
        self.error_collector = ErrorCollector()
        self.hard_generator = HardExampleGenerator(seed=seed)
        self.persona_injector = PersonaInjector(seed=seed)
        self.behavior_tree_expander = BehaviorTreeExpander(seed=seed)
        self.adversarial_generator = AdversarialGenerator(seed=seed)
        self.consistency_filter = ConsistencyFilter()
        
        self.all_generated: List[FlywheelSample] = []
        self.round_count = 0

    def record_errors(self, errors: List[Tuple[MathProblem, ModelResponse]]):
        """Record model errors for the next flywheel round."""
        for problem, response in errors:
            self.error_collector.record_error(problem, response)

    def generate_initial_data(self, counts: Optional[Dict[str, int]] = None) -> List[FlywheelSample]:
        """Generate initial training data (Round 0)."""
        from jiuzhang.curriculum_pipeline import CurriculumDataPipeline
        
        pipeline = CurriculumDataPipeline(seed=self.seed)
        if counts is None:
            counts = {1: 100, 2: 80, 3: 60, 4: 40}
        
        curriculum_samples = pipeline.generate_all_stages(counts)
        
        samples = []
        for cs in curriculum_samples:
            problem = MathProblem(
                id=f"curriculum_{cs.stage}_{cs.category}_{len(samples)}",
                category=cs.category,
                difficulty=DifficultyLevel(cs.difficulty) if cs.difficulty in [d.value for d in DifficultyLevel] else DifficultyLevel.ELEMENTARY,
                instruction_zh=cs.instruction_zh,
                instruction_en=cs.instruction_en,
                input_zh=cs.input_zh,
                input_en=cs.input_en,
                answer_zh=cs.output_zh,
                answer_en=cs.output_en,
                sympy_expression=str(cs.sympy_check) if cs.sympy_check else None,
            )
            
            sample = FlywheelSample(
                problem=problem,
                source="curriculum",
                verification_methods=["curriculum_verified"],
                verification_consensus=True,
            )
            samples.append(sample)
        
        self.all_generated.extend(samples)
        self.round_count = 0
        return samples

    def generate_next_round(self, 
                           expand_hard: bool = True,
                           inject_persona: bool = True,
                           expand_behavior_tree: bool = True,
                           generate_adversarial: bool = True,
                           max_new_samples: int = 100) -> List[FlywheelSample]:
        """Generate the next round of training data from errors."""
        self.round_count += 1
        new_samples = []
        errors = self.error_collector.errors
        
        if not errors:
            print(f"Round {self.round_count}: No errors recorded, skipping flywheel expansion.")
            return []
        
        # 1. Hard example generation from errors
        if expand_hard:
            hard_problems = self.hard_generator.generate_from_errors(errors, count_per_error=2)
            for prob in hard_problems:
                verified, methods = self.consistency_filter.verify_consensus(prob)
                if verified:
                    sample = FlywheelSample(
                        problem=prob,
                        source="error_expansion",
                        parent_problem_id=prob.id,
                        difficulty_increase=0.3,
                        verification_methods=methods,
                        verification_consensus=True,
                    )
                    new_samples.append(sample)
        
        # 2. Persona injection for diversity
        if inject_persona:
            for problem, response in errors[:10]:  # Limit to avoid explosion
                persona_problems = self.persona_injector.inject_all_personas(problem)
                for pp in persona_problems:
                    verified, methods = self.consistency_filter.verify_consensus(pp)
                    if verified:
                        sample = FlywheelSample(
                            problem=pp,
                            source="persona_injection",
                            parent_problem_id=problem.id,
                            difficulty_increase=0.0,  # Same difficulty, different context
                            verification_methods=methods,
                            verification_consensus=True,
                        )
                        new_samples.append(sample)
        
        # 3. Behavior tree expansion
        if expand_behavior_tree:
            for problem, response in errors[:5]:
                bt_problems = self.behavior_tree_expander.expand_problem(problem)
                for bp in bt_problems:
                    verified, methods = self.consistency_filter.verify_consensus(bp)
                    if verified:
                        sample = FlywheelSample(
                            problem=bp,
                            source="behavior_tree",
                            parent_problem_id=problem.id,
                            difficulty_increase=0.2,
                            verification_methods=methods,
                            verification_consensus=True,
                        )
                        new_samples.append(sample)
        
        # 4. Adversarial problem generation
        if generate_adversarial:
            for problem, response in errors[:5]:
                adv_problem = self.adversarial_generator.generate_adversarial(problem)
                verified, methods = self.consistency_filter.verify_consensus(adv_problem)
                if verified:
                    sample = FlywheelSample(
                        problem=adv_problem,
                        source="adversarial",
                        parent_problem_id=problem.id,
                        difficulty_increase=0.1,
                        verification_methods=methods,
                        verification_consensus=True,
                    )
                    new_samples.append(sample)
        
        # Cap total new samples
        if len(new_samples) > max_new_samples:
            new_samples = new_samples[:max_new_samples]
        
        self.all_generated.extend(new_samples)
        return new_samples

    def export_training_data(self, samples: Optional[List[FlywheelSample]] = None,
                            output_path: str = "jiuzhang_flywheel.jsonl",
                            format: str = "chatml"):
        """Export flywheel-generated samples to training format."""
        if samples is None:
            samples = self.all_generated
        
        with open(output_path, 'w', encoding='utf-8') as f:
            for sample in samples:
                if format == "chatml":
                    entry = {
                        "messages": [
                            {"role": "system", "content": f"你是九章数学专家。数据来源：{sample.source} / You are JiuZhang-Math. Source: {sample.source}"},
                            {"role": "user", "content": f"{sample.problem.instruction_zh}\n{sample.problem.input_zh}\n/\n{sample.problem.instruction_en}\n{sample.problem.input_en}"},
                            {"role": "assistant", "content": f"{sample.problem.answer_zh}\n/\n{sample.problem.answer_en}"},
                        ],
                        "source": sample.source,
                        "category": sample.problem.category,
                        "difficulty": sample.problem.difficulty.value,
                        "parent_problem_id": sample.parent_problem_id,
                        "difficulty_increase": sample.difficulty_increase,
                        "verification": sample.verification_methods,
                        "flywheel_round": self.round_count,
                    }
                else:
                    entry = {
                        "instruction": f"{sample.problem.instruction_zh} / {sample.problem.instruction_en}",
                        "input": f"{sample.problem.input_zh} / {sample.problem.input_en}",
                        "output": f"{sample.problem.answer_zh} / {sample.problem.answer_en}",
                        "source": sample.source,
                        "category": sample.problem.category,
                        "difficulty": sample.problem.difficulty.value,
                    }
                f.write(json.dumps(entry, ensure_ascii=False) + "\n")
        
        print(f"Exported {len(samples)} flywheel samples to {output_path}")

    def get_stats(self) -> Dict:
        """Get comprehensive flywheel statistics."""
        stats = {
            "total_samples": len(self.all_generated),
            "rounds_completed": self.round_count,
            "by_source": {},
            "by_category": {},
            "by_difficulty": {},
            "error_collector": self.error_collector.get_stats(),
            "verification_consensus_rate": 0.0,
        }
        
        consensus_count = 0
        for sample in self.all_generated:
            src = sample.source
            stats["by_source"][src] = stats["by_source"].get(src, 0) + 1
            
            cat = sample.problem.category
            stats["by_category"][cat] = stats["by_category"].get(cat, 0) + 1
            
            diff = sample.problem.difficulty.value
            stats["by_difficulty"][diff] = stats["by_difficulty"].get(diff, 0) + 1
            
            if sample.verification_consensus:
                consensus_count += 1
        
        if self.all_generated:
            stats["verification_consensus_rate"] = consensus_count / len(self.all_generated)
        
        return stats


# ── CLI Entry Point ──────────────────────────────────────────────────

def main():
    import argparse
    parser = argparse.ArgumentParser(description="JiuZhang Math Data Flywheel")
    parser.add_argument("--mode", choices=["generate", "round", "stats", "export"], default="generate")
    parser.add_argument("--output", default="jiuzhang_flywheel.jsonl")
    parser.add_argument("--format", choices=["chatml", "alpaca"], default="chatml")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--max-samples", type=int, default=200)
    args = parser.parse_args()

    flywheel = MathDataFlywheel(seed=args.seed)

    if args.mode == "generate":
        # Generate initial data
        samples = flywheel.generate_initial_data()
        print(f"Generated {len(samples)} initial samples")
        
        # Simulate some errors and generate next round
        for sample in samples[:10]:
            flywheel.record_errors([
                (sample.problem, ModelResponse(
                    problem_id=sample.problem.id,
                    response_zh="错误答案",
                    response_en="Wrong answer",
                    is_correct=False,
                    error_type="calculation",
                ))
            ])
        
        new_samples = flywheel.generate_next_round(max_new_samples=args.max_samples)
        print(f"Flywheel Round 1: Generated {len(new_samples)} new samples")
        
        # Export
        flywheel.export_training_data(output_path=args.output, format=args.format)
        
        # Stats
        import pprint
        print("\nFlywheel Statistics:")
        pprint.pprint(flywheel.get_stats())

    elif args.mode == "stats":
        flywheel.generate_initial_data()
        import pprint
        pprint.pprint(flywheel.get_stats())

    elif args.mode == "export":
        flywheel.generate_initial_data()
        flywheel.export_training_data(output_path=args.output, format=args.format)


if __name__ == "__main__":
    main()
