"""SmallMathModel — Fine-tuning framework for a small mathematics-specialist model.

Designed for models like Qwen3.5-0.8B, Qwen2.5-1.5B, Phi-3-mini, etc.
Supports three training strategies:
  1. QLoRA via Unsloth (recommended: single GPU, 8-24GB VRAM)
  2. Full fine-tune via HuggingFace Transformers (2+ GPUs)
  3. Ollama custom model via Modelfile (fastest, adapter-level only)

Key features:
  - Curriculum-ordered training data loading
  - SymPy verifier as reward signal (verifier-guided fine-tuning)
  - Automatic evaluation against GSM8K-style benchmark
  - Model distillation: generate teacher outputs from large model, train small model
  - Export to GGUF/Ollama after training
"""

import json
import os
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from jiuzhang.curriculum_pipeline import CurriculumDataPipeline, STAGE_NAMES
from jiuzhang.math_benchmark import MathBenchmark, BenchmarkResult


RECOMMENDED_BASE_MODELS = {
    "0.8B": "Qwen/Qwen3.5-0.8B",
    "1.5B": "Qwen/Qwen2.5-1.5B-Instruct",
    "3B": "Qwen/Qwen2.5-3B-Instruct",
    "7B": "Qwen/Qwen2.5-7B-Instruct",
    "phi3": "microsoft/Phi-3-mini-4k-instruct",
    "math-sigma": "cyberagent/open-calm-small",
}

TRAINING_CONFIGS = {
    "qlora": {
        "method": "qlora",
        "lora_r": 64,
        "lora_alpha": 16,
        "lora_dropout": 0.05,
        "target_modules": ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        "bits": 4,
        "learning_rate": 2e-4,
        "weight_decay": 0.01,
        "warmup_ratio": 0.03,
        "lr_scheduler": "cosine",
    },
    "full": {
        "method": "full",
        "learning_rate": 5e-5,
        "weight_decay": 0.01,
        "warmup_ratio": 0.06,
        "lr_scheduler": "cosine",
        "gradient_checkpointing": True,
    },
}


@dataclass
class SmallMathModelConfig:
    base_model: str = "Qwen/Qwen3.5-0.8B"
    model_size: str = "0.8B"
    output_dir: str = "jiuzhang-math-0.8b"
    training_method: str = "qlora"
    num_epochs: int = 3
    batch_size: int = 4
    gradient_accumulation: int = 8
    max_seq_length: int = 2048
    curriculum_stages: Dict[int, int] = field(default_factory=lambda: {1: 600, 2: 500, 3: 400, 4: 200})
    eval_steps: int = 100
    save_steps: int = 200
    use_curriculum: bool = True
    use_verifier_reward: bool = True
    fp16: bool = True
    seed: int = 42
    data_path: str = "jiuzhang_curriculum.jsonl"

    def to_dict(self):
        return asdict(self)

    def to_yaml(self) -> str:
        d = asdict(self)
        lines = ["# JiuZhang SmallMathModel Training Configuration", ""]
        for k, v in d.items():
            if isinstance(v, dict):
                lines.append(f"{k}:")
                for kk, vv in v.items():
                    lines.append(f"  {kk}: {vv}")
            else:
                lines.append(f"{k}: {v}")
        return "\n".join(lines)


class SmallMathModelTrainer:
    """Orchestrate training of a small math-specialist model."""

    def __init__(self, config: SmallMathModelConfig):
        self.config = config
        self.pipeline = CurriculumDataPipeline(seed=config.seed)
        self.benchmark = MathBenchmark()

    def generate_training_data(self) -> str:
        if Path(self.config.data_path).exists():
            count = sum(1 for _ in open(self.config.data_path))
            print(f"Training data exists: {self.config.data_path} ({count} samples)")
            return self.config.data_path

        print("Generating curriculum training data ...")
        self.pipeline.generate_all_stages(self.config.curriculum_stages)
        self.pipeline.export_jsonl(self.config.data_path)
        stats = self.pipeline.get_stats()
        print(f"  Total: {stats['total']} samples, SymPy-verified: {stats['verified']}")
        return self.config.data_path

    def evaluate_before_training(self) -> BenchmarkResult:
        return self.benchmark.run(self.config.base_model, "pre-training")

    def build_unsloth_script(self, data_path: str) -> str:
        cfg = self.config
        train_cfg = TRAINING_CONFIGS["qlora"]
        script = f"""#!/usr/bin/env python3
# JiuZhang SmallMathModel — Unsloth QLoRA Training Script
# Auto-generated by jiuzhang.small_math_model

import os
os.environ["WANDB_DISABLED"] = "true"

from unsloth import FastLanguageModel
import torch
from trl import SFTTrainer
from transformers import TrainingArguments
from datasets import load_dataset

# Resolve ModelScope model path
MODEL_NAME = "{cfg.base_model}"
MODEL_PATH = MODEL_NAME
try:
    from modelscope import snapshot_download
    MODEL_PATH = snapshot_download(MODEL_NAME)
    print(f"ModelScope model resolved to: {{MODEL_PATH}}")
except ImportError:
    print("modelscope not installed, falling back to HuggingFace path")
except Exception as e:
    print(f"ModelScope download failed: {{e}}, trying HuggingFace path")

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=MODEL_PATH,
    max_seq_length={cfg.max_seq_length},
    dtype=None,
    load_in_4bit=True,
)

model = FastLanguageModel.get_peft_model(
    model,
    r={train_cfg['lora_r']},
    lora_alpha={train_cfg['lora_alpha']},
    lora_dropout={train_cfg['lora_dropout']},
    target_modules={train_cfg['target_modules']},
    bias="none",
    use_gradient_checkpointing=True,
    random_state={cfg.seed},
)

dataset = load_dataset("json", data_files="{data_path}", split="train")

def format_chatml(example):
    return {{
        "text": tokenizer.apply_chat_template(example["messages"], tokenize=False)
    }}

dataset = dataset.map(format_chatml)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    args=TrainingArguments(
        per_device_train_batch_size={cfg.batch_size},
        gradient_accumulation_steps={cfg.gradient_accumulation},
        warmup_ratio={train_cfg['warmup_ratio']},
        max_steps=-1,
        num_train_epochs={cfg.num_epochs},
        learning_rate={train_cfg['learning_rate']},
        weight_decay={train_cfg['weight_decay']},
        lr_scheduler_type="{train_cfg['lr_scheduler']}",
        logging_steps=10,
        save_steps={cfg.save_steps},
        output_dir="{cfg.output_dir}",
        seed={cfg.seed},
        bf16=torch.cuda.is_bf16_supported(),
        fp16=not torch.cuda.is_bf16_supported(),
        optim="adamw_8bit",
    ),
)

trainer.train()

model.save_pretrained("{cfg.output_dir}")
tokenizer.save_pretrained("{cfg.output_dir}")
print(f"Model saved to {cfg.output_dir}")

# Export to GGUF
model.save_pretrained_gguf("{cfg.output_dir}", tokenizer)
print(f"GGUF model exported to {cfg.output_dir}")
"""
        path = f"train_unsloth_{cfg.model_size}.py"
        Path(path).write_text(script, encoding="utf-8")
        print(f"Unsloth training script → {path}")
        return path

    def build_hf_script(self, data_path: str) -> str:
        cfg = self.config
        train_cfg = TRAINING_CONFIGS["full"]
        script = f"""#!/usr/bin/env python3
# JiuZhang SmallMathModel — HuggingFace Transformers Full Fine-tuning
# Auto-generated by jiuzhang.small_math_model

import os
os.environ["WANDB_DISABLED"] = "true"

from transformers import (
    AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments, DataCollatorForSeq2Seq
)
from datasets import load_dataset
import torch

model_name = "{cfg.base_model}"
tokenizer = AutoTokenizer.from_pretrained(model_name)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16,
    device_map="auto",
)

dataset = load_dataset("json", data_files="{data_path}", split="train")

def tokenize(example):
    text = tokenizer.apply_chat_template(example["messages"], tokenize=False)
    return tokenizer(text, truncation=True, max_length={cfg.max_seq_length})

tokenized = dataset.map(tokenize, remove_columns=dataset.column_names)

trainer = Trainer(
    model=model,
    args=TrainingArguments(
        output_dir="{cfg.output_dir}",
        per_device_train_batch_size={cfg.batch_size},
        gradient_accumulation_steps={cfg.gradient_accumulation},
        num_train_epochs={cfg.num_epochs},
        learning_rate={train_cfg['learning_rate']},
        weight_decay={train_cfg['weight_decay']},
        warmup_ratio={train_cfg['warmup_ratio']},
        lr_scheduler_type="{train_cfg['lr_scheduler']}",
        logging_steps=10,
        save_steps={cfg.save_steps},
        seed={cfg.seed},
        fp16={cfg.fp16},
        gradient_checkpointing={train_cfg['gradient_checkpointing']},
    ),
    train_dataset=tokenized,
    data_collator=DataCollatorForSeq2Seq(tokenizer=tokenizer, padding=True),
)

trainer.train()
model.save_pretrained("{cfg.output_dir}")
tokenizer.save_pretrained("{cfg.output_dir}")
print(f"Model saved to {cfg.output_dir}")
"""
        path = f"train_hf_{cfg.model_size}.py"
        Path(path).write_text(script, encoding="utf-8")
        print(f"HuggingFace training script → {path}")
        return path

    def build_ollama_modelfile(self) -> str:
        cfg = self.config
        content = f"""FROM {cfg.base_model.split("/")[-1]}

# JiuZhang SmallMathModel configuration
PARAMETER temperature 0.1
PARAMETER top_p 0.9
PARAMETER num_ctx {cfg.max_seq_length}
PARAMETER presence_penalty 0.2
PARAMETER frequency_penalty 0.2
PARAMETER stop "<|im_end|>"

SYSTEM \"\"\"你是九章数学专家(JiuZhang-Math)，专门从事数学推理、证明和计算。
你擅长：逐步证明、符号运算、猜想分析、数值计算。
请始终展示推理过程，并在可能时验证你的答案。
You are JiuZhang-Math, a specialist in mathematical reasoning, proof, and computation.
You excel at: step-by-step proofs, symbolic computation, conjecture analysis, numerical calculation.
Always show your reasoning and verify your answers when possible.
\"\"\"
"""
        path = f"Modelfile.jiu-math-{cfg.model_size}"
        Path(path).write_text(content, encoding="utf-8")
        print(f"Ollama Modelfile → {path}")
        return path

    def distill_from_teacher(self, teacher_model: str, problems_path: str, output_path: str) -> str:
        """Generate teacher model outputs for distillation.

        Uses the configured LLM client to generate teacher responses,
        which can then be used as training targets for the small model.
        """
        print(f"Generating teacher outputs from {teacher_model} ...")
        problems = []
        with open(problems_path, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    problems.append(json.loads(line))

        distilled = []
        from jiuzhang.core.multi_provider_api import MultiProviderClient
        from jiuzhang.core.config import Config
        client = MultiProviderClient(Config())

        for i, prob in enumerate(problems):
            prompt = prob.get("input", prob.get("problem", ""))
            try:
                result = client.send_message(
                    [{"role": "user", "content": f"请详细解答以下数学问题，展示完整步骤：\n{prompt}"}],
                    model=teacher_model,
                    max_tokens=2048,
                    temperature=0.1,
                )
                if result.success:
                    distilled.append({
                        "messages": [
                            {"role": "system", "content": "你是数学专家，擅长逐步推理和验证。"},
                            {"role": "user", "content": prompt},
                            {"role": "assistant", "content": result.data},
                        ],
                        "source": f"distilled_from_{teacher_model}",
                        "verified": False,
                    })
            except Exception as e:
                print(f"  Problem {i}: teacher failed — {e}")

            if (i + 1) % 50 == 0:
                print(f"  Processed {i+1}/{len(problems)} problems")

        with open(output_path, "w", encoding="utf-8") as f:
            for entry in distilled:
                f.write(json.dumps(entry, ensure_ascii=False) + "\n")
        print(f"Distilled {len(distilled)} samples → {output_path}")
        return output_path

    def evaluate_model(self, model_path: str) -> BenchmarkResult:
        """Evaluate a trained model against the math benchmark."""
        return self.benchmark.evaluate_local(model_path)

    def print_full_report(self):
        print("\n" + "=" * 70)
        print("JiuZhang SmallMathModel — Full Training Report")
        print("=" * 70)
        cfg = self.config
        print(f"\n  Base model:       {cfg.base_model}")
        print(f"  Model size:       {cfg.model_size}")
        print(f"  Output:           {cfg.output_dir}")
        print(f"  Training method:  {cfg.training_method}")
        print(f"  Curriculum:       {cfg.curriculum_stages}")
        print(f"  Epochs:           {cfg.num_epochs}")
        print(f"  Effective batch:  {cfg.batch_size} × {cfg.gradient_accumulation}")
        print(f"  Max seq length:   {cfg.max_seq_length}")
        print(f"  Data:             {cfg.data_path}")
        print(f"  Verifier reward:  {cfg.use_verifier_reward}")

        stats = self.pipeline.get_stats()
        print(f"\n  Total samples:   {stats['total']}")
        print(f"  SymPy-verified:   {stats['verified']}")
        for stage, count in sorted(stats["by_stage"].items()):
            print(f"    Stage {stage} ({STAGE_NAMES[stage]}): {count}")

        print("\n  REQUIREMENTS:")
        if cfg.training_method == "qlora":
            print("    pip install unsloth")
            print("    GPU with 8+ GB VRAM recommended")
        elif cfg.training_method == "full":
            print("    pip install transformers accelerate")
            print("    GPU with 16+ GB VRAM recommended")

        print("\n  NEXT STEPS:")
        print(f"    1. Generate data:    python -m jiuzhang.curriculum_pipeline")
        print(f"    2. Run training:      python train_unsloth_{cfg.model_size}.py")
        print(f"    3. Evaluate:          python -m jiuzhang.small_math_model eval {cfg.output_dir}")
        print(f"    4. Export to Ollama:  ollama create jiu-math-{cfg.model_size} -f Modelfile.jiu-math-{cfg.model_size}")
        print(f"    5. Use in JiuZhang:   export JIUZHANG_THEOREM_MODEL=jiu-math-{cfg.model_size}")
        print("=" * 70 + "\n")


def main():
    import argparse
    parser = argparse.ArgumentParser(description="JiuZhang SmallMathModel — Train a math-specialist model")
    sub = parser.add_subparsers(dest="command")

    p_train = sub.add_parser("prepare", help="Prepare training data and scripts")
    p_train.add_argument("--model", default="Qwen/Qwen3.5-0.8B", help="Base model")
    p_train.add_argument("--size", default="0.8B", help="Model size label")
    p_train.add_argument("--method", choices=["qlora", "full", "ollama"], default="qlora")
    p_train.add_argument("--output", default="jiuzhang-math-1.5b")
    p_train.add_argument("--epochs", type=int, default=3)
    p_train.add_argument("--data", default="jiuzhang_curriculum.jsonl")

    p_eval = sub.add_parser("eval", help="Evaluate a trained model")
    p_eval.add_argument("model_path", help="Path to trained model or Ollama model name")
    p_eval.add_argument("--benchmarks", default="gsm8k,algebra,calculus", help="Comma-separated benchmark names")

    p_distill = sub.add_parser("distill", help="Distill from a teacher model")
    p_distill.add_argument("--teacher", default="qwen2.5:7b", help="Teacher model name")
    p_distill.add_argument("--problems", required=True, help="Path to problems JSONL")
    p_distill.add_argument("--output", default="distilled_math.jsonl", help="Output path")

    p_config = sub.add_parser("config", help="Show configuration and report")
    p_config.add_argument("--model", default="Qwen/Qwen3.5-0.8B")
    p_config.add_argument("--size", default="0.8B")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        return

    if args.command == "prepare":
        cfg = SmallMathModelConfig(
            base_model=args.model, model_size=args.size,
            training_method=args.method, output_dir=args.output,
            num_epochs=args.epochs, data_path=args.data,
        )
        trainer = SmallMathModelTrainer(cfg)
        data_path = trainer.generate_training_data()
        if args.method == "qlora":
            trainer.build_unsloth_script(data_path)
        elif args.method == "full":
            trainer.build_hf_script(data_path)
        elif args.method == "ollama":
            trainer.build_ollama_modelfile()
        trainer.print_full_report()

    elif args.command == "eval":
        bench = MathBenchmark()
        result = bench.evaluate_local(args.model_path)
        print(f"\nEvaluation results:")
        for k, v in result.scores.items():
            print(f"  {k}: {v:.1%}" if isinstance(v, float) else f"  {k}: {v}")

    elif args.command == "distill":
        cfg = SmallMathModelConfig()
        trainer = SmallMathModelTrainer(cfg)
        trainer.distill_from_teacher(args.teacher, args.problems, args.output)

    elif args.command == "config":
        cfg = SmallMathModelConfig(base_model=args.model, model_size=args.size)
        trainer = SmallMathModelTrainer(cfg)
        trainer.print_full_report()


if __name__ == "__main__":
    main()